config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :topics, except: :destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic

    validates :title, presence: true
    validates :author, presence: true
    validates :content, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts

    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
      @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(strong_params)
    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(strong_params)
    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to posts_path
  end

  private

  def strong_params
    params.require(:post).permit(:title, :author, :content, :topic_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.create(strong_params)
    if @topic.errors.empty?
      redirect_to @topic
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update(strong_params)
    if @topic.errors.emtpy?
      redirect_to topic_path(@topic)
    else
      render :edit
    end
  end

  private

  def strong_params
    params.require(:topic).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostAppMod2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_form.html.erb
<div>
<%= form_for @post do |p| %>

    <%= p.label :topic %>
    <%= p.collection_select(:topic_id, Topic.all, :id, :name, {:prompt => 'Select a Topic'}) %>

    <%= p.label :title %>
    <%= p.text_field :title %>

    <%= p.label :author %>
    <%= p.text_field :author %>

    <%= p.label :content %>
    <%= p.text_area :content %>

    <%= p.submit button_text %>

<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit this Post</h1>

<%= render partial: "shared/error_list", locals: {obj: @post} %>

<%= render partial: "post_form", locals: {button_text: "Edit Post"} %>

app/views/posts/index.html.erb
<h1>All the Posts</h1>

<ul>
    <% @posts.each do |p| %>
        <li><%= link_to p.title, post_path(p) %></li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Write a New Post</h1>

<%= render partial: "shared/error_list", locals: {obj: @post} %>

<%= render partial: "post_form", locals: {button_text: "Publish Post"} %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h2><%= @post.author %></h2>

<p><%= @post.content %></p>

<div>
    <%= link_to "Edit this post", edit_post_path(@post) %>
</div>

<p><%= form_tag post_path(@post), method: "DELETE" do %>
    <%= submit_tag "Delete Post" %></p>
<% end %>

<%= link_to "View all posts", posts_path %>

app/views/shared/_error_list.html.erb
<% if obj.errors %>
    <ul class="error-list">
        <% obj.errors.full_messages.each do |message| %>
            <li class="error"><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/topics/_topic_form.html.erb
<div>
<%= form_for @topic do |t| %>

    <%= t.label :name %>
    <%= t.text_field :name %>

    <%= t.label :description %>
    <%= t.text_field :description %>

    <%= t.submit button_text %>

<% end %>
</div>

app/views/topics/edit.html.erb
<h1>Edit this Topic</h1>

<%= render partial: "shared/error_list", locals: {object: @topic} %>

<%= render partial: "topic_form", locals: {button_text: "Edit Topic"} %>

app/views/topics/index.html.erb
<h1>All the Topics</h1>

<ul>
    <% @topics.each do |t| %>
        <li><%= link_to t.name, topic_path(t) %></li>
    <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Create a New Topic</h1>

<%= render partial: "shared/error_list", locals: {obj: @topic} %>

<%= render partial: "topic_form", locals: {button_text: "Create Topic"} %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<h2><%= @topic.description %></h2>

<h2>Posts</h2>
<ul>
    <% @topic.posts.each do |p| %>
        <li><%= link_to p.title, post_path(p) %></li>
    <% end %>
</ul>

<div>
    <%= link_to "Edit this topic", edit_topic_path(@topic) %>
    <%= link_to "View all topics", topics_path %>
</div>